version: '3'
services:
  frontend:
    build:
      context: ./movieView
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./movieDB
    ports:
      - "8080:8080"
    # depends_on:
    #   - mongo
    
#   db:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

