services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: movie_db
    ports:
      - "27017:27017"
    networks:
      - app-network  # 加入自定义网络
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  backend:
    build: ./movieDB
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/movie_db?authSource=admin
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - app-network  # 加入自定义网络

  frontend:
    build: ./movieView
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    restart: always
    networks:
      - app-network  # 加入自定义网络

volumes:
  mongodb_data:

# 定义共享网络
networks:
  app-network:
