services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: movie_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ../mongo-init:/docker-entrypoint-initdb.d

  backend:
    image: stupidfalcon/moviedb-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/movie_db?authSource=admin
    depends_on:
      - mongodb
    restart: on-failure

  frontend:
    image: stupidfalcon/moviedb-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data: