name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker compose up
      run: docker compose up -d --build
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/moviedb-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/moviedb-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mongo:latest
        
